<?php


/**
 * Implements of hook_menu().
 */
function drugular_menu() {
  $items = array();

  $items['test'] = array(
    'title' => 'Test page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => '_something',
  );

  return $items;
}


/**
 * Implements of hook_theme().
 */
function drugular_theme() {
	$themes = array (
		'_test_theme' => array(
      'template' => 'test-something', 
      'path' => drupal_get_path('module', 'drugular') . '/templates',
		),
	);
	return $themes;
}

function _something() {
  print theme('_test_theme');
}